// project/components/organisms/header/Header.vue
<template>
    <header id="Header" class="header">
      <Container>
        <LogoDark/>
        <nav class="navLinks">
          <a class="linkHeader" href="#">Inicio</a>
          <a class="linkHeader" href="#About">Sobre mim</a>
          <a class="linkHeader" href="#Portfolio">Portfólio</a>
          <a class="linkHeader" href="#Contact">Contato</a>
          <a class="linkHeader" href="#">Darkmode</a>
        </nav>
        <ButtonGradient>
          <a href="#">Entrar em contato</a> 
        </ButtonGradient>
      </Container>
    </header>
</template>

<style lang="scss" scoped>
  #Header {
    padding: 2rem;
    position: fixed;
    top: 0;
    display: flex;
    width: 100%;
    border-bottom: solid 2px #E7E7E7;
    background-color: #EDEDED77;
    -webkit-backdrop-filter: blur(25px);
    backdrop-filter: blur(25px);
    z-index: 100;

    .container{
      display : flex;
      align-items : center;
      justify-content: space-between;

      .navLinks{
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 5rem;

        .linkHeader{
          display: block;
          text-align: center;
          color: var(--dark-base);
          transition: 0.3s;
        }

        .linkHeader:hover{
          color: var(--green);
        }
      }
    }
  }
</style>

// project/src/components/organisms/Header/index.tsx
import { Container } from "../../atoms/Container";
import styled from "styled-components";
import { ButtonDegrade, Link, LogoDark, ToogleSwitch } from "../..";

export function Header() {
  return (
    <StyledHeader>
      <Container>
        <LogoDark/>
        <nav>
          <Link href="#Hero">Início</Link>
          <Link href="#SobreMim">Sobre mim</Link>
          <Link href="#Portfolio">Potifólio</Link>
          <ToogleSwitch>Dark Mode</ToogleSwitch>
        </nav>
        <ButtonDegrade href="#Contact">
          Entrar em contato
        </ButtonDegrade>
      </Container>
    </StyledHeader>
  );
}

const StyledHeader = styled.header`
  padding: 1.8rem;
  position: fixed;
  top: 0;
  display: flex;
  width: 100%;
  border-bottom: solid 2px #b4b4b466;
  background-color: #ededed77;
  -webkit-backdrop-filter: blur(25px);
  backdrop-filter: blur(25px);
  z-index: 100;
  div {
    margin: 0 auto;
    width: 123.4rem;
    display: flex;
    align-items: center;
    justify-content: space-between;
    nav {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 4rem;
    }
  }
`;
