// project/src/components/organisms/Footer/index.tsx
import styled from "styled-components";
import { Container, LogoLight, SpanTextLight } from "../..";

export function Footer() {
  return (
    <StyledFooter>
      <Container>
        <SpanTextLight>
          Copyright &copy; 2021 - Alguns direitos reservados a
          <LogoLight />
        </SpanTextLight>
      </Container>
    </StyledFooter>
  );
}

const StyledFooter = styled.footer`
  padding: 3rem 0;
  background-color: var(--dark-100);
  div{
    display: flex;
    justify-content: center;
    align-items: center;
  }
`;

// project/components/organisms/footer/Footer.vue
<template>
  <footer id="Footer" class="footer">
    <Container>
      <p>Copyright &copy; {{currentYear}} - Alguns direitos reservados a</p>
      <LogoLight/>
    </Container>
  </footer>
</template>

<script lang="ts">
  export default{
    computed: {
      currentYear(){
        return new Date().getFullYear()
      }
    }
  }
</script>

<style lang="scss" scoped>
  #Footer{
    padding: 3rem 0;
    display: flex;
    justify-content: center;
    background-color: var(--dark-base);
    .container{
      display: flex;
      justify-content: center;
      align-items : center;
      gap: 1rem;
      p{
        font-weight: 400;
        color: var(--white-base)
      }
    }
  }
</style>
