// project/components/molecules/TextArea.vue
<template>
  <div class="inputGroup">
    <label>
      {{ label }}
      <textarea :type="type" :placeholder="placeholder" :value="value" />
    </label>
  </div>
</template>

<script lang="ts">
export default {
  props: {
    label: { type: String, required: true },
    type: { type: String, required: true },
    placeholder: { type: String, required: true },
    value: { type: String, required: true }
  }
}
</script>

<style lang="scss" scoped>
.inputGroup {
  label {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }
  textarea {
    font-family: 'Epilogue', sans-serif;
    font-style: normal;
    font-weight: normal;
    font-size: 16px;
    line-height: 16px;
    border-radius: 0.5rem;
    padding: 1.7rem 2.5rem;
    resize: none;
    height: 15rem;
    background-color: var(--white-medium);
    border: 1px solid var(--white-medium);
    transition: 0.3s;

    &:focus {
      outline: none;
      border: 1px solid var(--green);
    }
  }
}
</style>

// project/src/components/atoms/TextArea/index.tsx
import styled from "styled-components";

interface iInputProps {
  label: string;
  name: string;
  placeholder: string;
  maxlength: number;
  minlength: number;
  heigth: string;
}

export function TextArea(props: iInputProps) {
  const { label, name, placeholder, minlength, maxlength, heigth } = props;
  return (
    <StyledTextArea heigth={heigth}>
      {label}
      <textarea
        id={name}
        name={name}
        placeholder={placeholder}
        minLength={minlength}
        maxLength={maxlength}
      />
    </StyledTextArea>
  );
}

interface iStyledTextAreaProps {
  heigth: string;
}

const StyledTextArea = styled.label<iStyledTextAreaProps>`
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
  font-style: normal;
  font-weight: normal;
  font-size: 16px;
  line-height: 16px;
  color: var(--dark-100);
  textarea {
    border-radius: 0.5rem;
    resize: none;
    height: ${props =>  props.heigth};
    padding: 1.5rem 2.5rem;
    font-style: normal;
    font-weight: normal;
    font-size: 16px;
    line-height: 16px;
    color: #04041322;
    background-color: var(--white-80);
    transition: 0.3s;
    border:solid 2px var(--white-80);
    &:focus{
      outline: transparent;
      border:solid 2px var(--green);
    }
  }
`;
