// project/components/organisms/hero/Hero.vue
<template>
  <section id="Hero">
    <Container>
      <aside class="heroTextContainer">
        <Description>Alexandre Shyjada</Description>
        <MainTitle>Designer UI/UX e Desenvolvedor Web</MainTitle>
        <MainParagrath>
          A sua disposição para desenvolver soluções em tecnologia que atendam as
          necessidades de seu negócio
        </MainParagrath>
        <div class="btnGroup">
          <ButtonGradient><a href="#">Entrar em contato</a></ButtonGradient>
          <ButtonWhite><a href="#">Currículo CV</a></ButtonWhite>
        </div>
      </aside>

      <figure>
        <img src="/assets/img-hero.svg" alt="Designer UI/UX e Desenvolvedor Web"/>
      </figure>
    </Container>
  </section>
</template>

<script lang="ts">
  export default {}
</script>

<style lang="scss" scoped>
  #Hero {
    margin-top: 8.8rem;
    padding: 5.5rem 0;
    display: flex;
    align-items: center;
    gap: 8rem;

    .container {
      display: flex;
      align-items : center;
      flex-direction: row;
      gap: 8rem;

      aside{
        display: flex;
        flex-direction: column;

        .mainTitle{
          margin: 2rem 0;
        }
        
        .btnGroup {
          margin-top: 3rem;
          display: flex;
          gap: 2.5rem;
        }
      }
    }
  }


</style>

// project/src/components/organisms/Hero/index.tsx
import styled from "styled-components";
import {
  ButtonDegrade,
  ButtonWhite,
  Container,
  H1,
  ImgHeroLight,
  SpanTextDark,
  UpercaseText,
} from "../..";

export function Hero() {
  return (
    <StyledHero id="Hero">
      <Container>
        <aside>
          <UpercaseText>Alexandre Shyjada</UpercaseText>
          <H1>Designer UI/UX e Desenvolvedor Web</H1>
          <SpanTextDark>
            A sua disposição para desenvolver soluções em tecnologia que atendam
            as necessidades de seu negócio
          </SpanTextDark>
          <div className="buttonGroup">
            <ButtonDegrade href="#Contact">Entrar em contato</ButtonDegrade>
            <ButtonWhite href="https://curriculo.alexshyjada.com/">
              Currículo CV
            </ButtonWhite>
          </div>
        </aside>
        <ImgHeroLight />
      </Container>
    </StyledHero>
  );
}

const StyledHero = styled.section`
  margin-top: 8.24rem;
  padding: 5rem;
  div {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
    aside {
      width: 52.5rem;
      display: flex;
      flex-direction: column;
      gap: 1.5rem;
      .buttonGroup{
        display: flex;
        justify-content: flex-start;
        gap: 2.5rem;
      }
    }
  }
`;
