// project/components/organisms/portfolio/Portfolio.vue
<template>
  <section id="Portfolio" class="portfolio">    
    <Container>
      <TitleGroup
        title="Projetos desenvolvidos por mim"
        description="Portfólio"
      />
      <div class="cardsContainer">
        <PortfolioCard
          img="/assets/project-SurfSsa.png"
          title="SurfSsa"
          description="Projeto construído para a SurfSsa, empresa de surf na capital Baiana."
          url="https://www.behance.net/gallery/119621147/Surf-Salvador"
        />
        <PortfolioCard
          img="/assets/project-SurfSsa.png"
          title="SurfSsa"
          description="Projeto construído para a SurfSsa, empresa de surf na capital Baiana."
          url="https://www.behance.net/gallery/119621147/Surf-Salvador"
        />
        <PortfolioCard
          img="/assets/project-SurfSsa.png"
          title="SurfSsa"
          description="Projeto construído para a SurfSsa, empresa de surf na capital Baiana."
          url="https://www.behance.net/gallery/119621147/Surf-Salvador"
        />
        <PortfolioCard
          img="/assets/project-SurfSsa.png"
          title="SurfSsa"
          description="Projeto construído para a SurfSsa, empresa de surf na capital Baiana."
          url="https://www.behance.net/gallery/119621147/Surf-Salvador"
        />
        <PortfolioCard
          img="/assets/project-SurfSsa.png"
          title="SurfSsa"
          description="Projeto construído para a SurfSsa, empresa de surf na capital Baiana."
          url="https://www.behance.net/gallery/119621147/Surf-Salvador"
        />
      </div>
      <div class="btnGroup">
        <ButtonWhite>
          Anterior
        </ButtonWhite>
        <ButtonGradient>
          Próximo
        </ButtonGradient>
      </div>
    </Container>

    
  </section>
</template>

<style lang="scss" scoped>

  .portfolio{
    padding: 8rem 0;
    display: flex;
    flex-direction: column;
    gap: 6rem;
    .container {
      display: flex;
      flex-direction: column;
      gap: 6rem;
      .btnGroup{
        display: flex;
        justify-content: space-between;
        flex-direction: row;
        .btnGrad{
          width: 18.5rem;
        }
        .btnWhite{
          width: 18.5rem;
        }
      }
    }
    .cardsContainer{
      display: flex;
      flex-direction: row;gap: 2.5rem;
    }
  }

</style>

// project/src/components/organisms/Portfolio/index.tsx
import styled from "styled-components";
import {
  ButtonDegrade,
  ButtonWhite,
  CardPortfolio,
  Container,
  TitleContainer,
} from "../..";

type Portfolio = {
  slug: string;
  image: string;
  title: string;
  description: string;
  linkDribbble: string;
};

interface IPortfolioProps {
  portfolio: Portfolio[];
}

export function Portfolio({ portfolio }: IPortfolioProps) {
  return (
    <StyledPortfolio>
      <Container>
        <TitleContainer
          title="Projetos desenvolvidos por mim"
          subTitle="PORTFÓLIO"
        />
      </Container>
      <div className="gridCardsContainer">
        <Container>
          <div className="gridCards">
            {portfolio.map((card) => (
              <CardPortfolio
                key={card.slug}
                imgSRC={card.image}
                title={card.title}
                description={card.description}
                linkDribbble={card.linkDribbble}
              />
            ))}
          </div>
        </Container>
      </div>
      <Container>
        <ButtonWhite width="185px">Anterior</ButtonWhite>
        <ButtonDegrade width="185px">Próximo</ButtonDegrade>
      </Container>
    </StyledPortfolio>
  );
}

const StyledPortfolio = styled.section`
  display: flex;
  flex-direction: column;
  gap: 6rem;
  .container {
    display: flex;
    justify-content: space-between;
  }
  .gridCardsContainer {
    display: flex;
    flex-direction: row;
    overflow: hidden;
    .container {
      display: block;
      overflow: visible;
      .gridCards {
        display: flex;
        flex-direction: row;
        gap: 2.5rem;
      }
    }
  }
`;
