// project/src/components/atoms/Input/index.tsx
import styled from "styled-components";

interface iInputProps {
  label: string;
  type: string;
  name: string;
  placeholder: string;
}

export function Input(props: iInputProps) {
  const { label, type, name, placeholder } = props;
  return (
    <StyledInput>
      {label}
      <input type={type} name={name} placeholder={placeholder} />
    </StyledInput>
  );
}

const StyledInput = styled.label`
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
  font-style: normal;
  font-weight: normal;
  font-size: 16px;
  line-height: 16px;
  color: var(--dark-100);
  input {
    padding: 1.5rem 2.5rem;
    width: 100%;
    font-style: normal;
    font-weight: normal;
    font-size: 16px;
    line-height: 16px;
    color: #04041322;
    border-radius: 0.5rem;
    border: solid 2px var(--white-80);
    background-color: var(--white-80);
    transition: 0.3s;
    &:focus{
      outline: transparent;
      border: solid 2px var(--green);
    }
  }
`;

// project/components/molecules/Input.vue
<template>
  <div class="inputGroup">
    <label>
      {{ label }}
      <input :type="type" :placeholder="placeholder" :value="value" />
    </label>
  </div>
</template>

<script lang="ts">
export default {
  props: {
    label: { type: String, required: true },
    type: { type: String, required: true },
    placeholder: { type: String, required: true },
    value: { type: String, required: true }
  }
}
</script>

<style lang="scss" scoped>
.inputGroup {
  label {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }
  input {
    font-family: 'Epilogue', sans-serif;
    font-style: normal;
    font-weight: normal;
    font-size: 16px;
    line-height: 16px;
    border-radius: 0.5rem;
    padding: 1.7rem 2.5rem;
    background-color: var(--white-medium);
    border: 1px solid var(--white-medium);
    transition: 0.3s;

    &:focus {
      outline: none;
      border: 1px solid var(--green);
    }
  }
}
</style>
